name: Django CI

on:
  push:
  #branches: ["master"] 
  # * means all branches 
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9 
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Coverage report
      run: |
        coverage run manage.py test
        coverage report
    - name: Run Tests
      run: |
         python manage.py test
